### ISSUE TITLE
Undefined offset: 0

### ISSUE THREAD

**Issue by FranRomero** [Finnb8r/itunes-connect-sales-api-php#1]
I am trying to get Montly reports but I am not able to get them. This is the code that I have by the moment:

```
<?php

require_once('itunesconnectapi/class/iTunesSalesApi.php');

$reporter = new iTunesSalesApi("user","password","idVendor");

$reporter = new iTunesSalesApi();
$reporter->setLogin("user")
            ->setPassword("password")
            ->setVendor("idVendor")
            ->setFolder("C:\xampp\htdocs\stats")
            ->setUseCache(true)
            ->setReportModeAll();

try{
    if($data = $reporter->getSalesMonthlyReport()) {
        print_r(json_encode($data));
    }
    else{
        echo "Api  Errors : ".$reporter->getErrorsAsString();
    }
}catch (Exception $e){
    echo $e->getMessage();
}
```

but this error is shown on the screen:

> Notice: Undefined offset: 0 in C:\xampp\htdocs\stats\itunesconnectapi\class\iTunesSalesApi.php on line 604
> Unknown error has ocured (http code 0 )

I have this error for any information I try to get from my iTunnes Connect. I am using XAMPP as local server so I do not know if it can be related with the issue.

What should I do to solve this problem?

Thanks in advance!

**Comment by Finnb8r** [comment]
Hi FranRomero,
Thank you for your feedback !
First observation : you don't need to instantiate your object twice, my example is maybe a bit confusing : you can remove the first `$reporter = new iTunesSalesApi("user","password","idVendor");` as you create the object again on the next line.
Regarding your specific error, it most likely would be a cUrl error. The api uses curl to call iTunes servers, the error code 0, from the message "Unknow error has occured (http code 0)" usulally indicates that the request could not have been made.
Make sure you have curl enabled on your xampp configuration, here is a link that might help : [http://stackoverflow.com/questions/3020049/how-to-enable-curl-in-xampp](url)

Let me know if all is ok and good luck !

**Comment by FranRomero** [comment]
Hi Finnb8r,
Thank you for your quick answer!

I have checked that CURL is enabled on XAMPP and I removed the first object contructor as you suggested but the error persists. I am not familiar with CURL so I do not know if I have to modify any additional file.

Thanks again for your suggestions!

**Comment by Finnb8r** [comment]
Re,

I have just commited a small change to the file iTunesSalesApi.php 
If you can checkout the lastest version, the error should now be a bit more specific.

If the error is related to SSL, you can disable SSL checks by calling (after you have updated to latest version):
`$reporter->disableCurlSSL = true;` just after `$reporter = new iTunesSalesApi();`

Keep me posted

**Comment by FranRomero** [comment]
Hi,

I have added the line that you suggested (after downloading the new version) and now a new error have appeared:

> Unknown error has ocured (http code 404 )

The error that I had before has dissapeared, though.

Thanks for your quick replies!

**Comment by Finnb8r** [comment]
Great, there's progress ;)

Last little thing and we should get the specific error : I have just pushed another minor commit that changes the file iTunesSalesApi.php.
If you checkout the lastest version, there should be a specific error message along with the error code.
Sorry for any inconvenience and this step by step debugging...

**Comment by FranRomero** [comment]
Hi!

Thanks again for your quick answer!

Now, with your last commit the error its much more intuitive:

> Unknown error has ocured (http code 404, content : There were no sales for the date specified. )

so I notice that I had not stats for last month because I published the application on February so I understand why this error happens right now.

According to the fail that I had before, I have changed my code to get weekly stats but a new error happened:

> Warning: file_put_contents(\C:\Users\Fran\AppData\Local\Temp\S_S_W_87386320_20170219.txt): failed to open stream: Invalid argument in C:\xampp\htdocs\stats\itunesconnectapi\class\iTunesSalesApi.php on line 663
> 
> Warning: fopen(\C:\Users\Fran\AppData\Local\Temp\S_S_W_87386320_20170219.txt): failed to open stream: Invalid argument in C:\xampp\htdocs\stats\itunesconnectapi\class\iTunesSalesApi.php on line 696
> 
> Warning: feof() expects parameter 1 to be resource, boolean given in C:\xampp\htdocs\stats\itunesconnectapi\class\iTunesSalesApi.php on line 702
> 
> Warning: fgets() expects parameter 1 to be resource, boolean given in C:\xampp\htdocs\stats\itunesconnectapi\class\iTunesSalesApi.php on line 705
> 
> Warning: feof() expects parameter 1 to be resource, boolean given in C:\xampp\htdocs\stats\itunesconnectapi\class\iTunesSalesApi.php on line 702
> 
> Warning: fgets() expects parameter 1 to be resource, boolean given in C:\xampp\htdocs\stats\itunesconnectapi\class\iTunesSalesApi.php on line 705

and these two last lines are repeteaded around 1000+ times.

I thought that these errors were related about cache but I have deleted the lines refered to cache and the error persists.

This is the code that I have now:

```
<?php

require_once('itunesconnectapi/class/iTunesSalesApi.php');

$reporter = new iTunesSalesApi("user","password","idVendor");

$reporter = new iTunesSalesApi();
$reporter->setLogin("user")
            ->setPassword("password")
            ->setVendor("idVendor")
            ->setReportModeAll();

try{
    if($data = $reporter->getSalesWeeklyReport()) {
        print_r(json_encode($data));
    }
    else{
        echo "Api  Errors : ".$reporter->getErrorsAsString();
    }
}catch (Exception $e){
    echo $e->getMessage();
}
```

Thanks again for you help!

**Comment by Finnb8r** [comment]
Okay, I have done another commit...
The class uses the function gzdecode but this function is not always available.; I have changed it to gzinflate which should be better.
I have also added a check on file opening to prevent 1000+ lines of errors, sorry about that.
Everything should work now, sorry again for the inconvenience but thanks for being a true tester !

**Comment by FranRomero** [comment]
Now there are just two errors about opening a file (one is the same as before). Here I add both errors:

> Warning: file_put_contents(\C:\Users\Fran\AppData\Local\Temp\S_S_W_87386320_20170219.txt): failed to open stream: Invalid argument in C:\xampp\htdocs\stats\itunesconnectapi\class\iTunesSalesApi.php on line 663
> Unable to open file \C:\Users\Fran\AppData\Local\Temp\S_S_W_87386320_20170219.txt
> Warning: unlink(\C:\Users\Fran\AppData\Local\Temp\S_S_W_87386320_20170219.txt): Invalid argument in C:\xampp\htdocs\stats\itunesconnectapi\class\iTunesSalesApi.php on line 666

Thanks again!

**Comment by Finnb8r** [comment]
Ok, the error seems to be specific to the local environment. When looking at the file path, it starts with a "\" which should not be there. For example on our linux servers, the tmp path is mostly "\tmp" but on your local machine it's "C:\Users\....".
I have updated the path to try with and without the "\" at the beginning of the path.
Everything should work now (once you checkout the latest version) !

**Comment by FranRomero** [comment]
Now it is retrieving me the JSON with the information. Thank you very much!

**Just a note:**  Some values of the JSON are not enconding well when they have accents. I think you should use **utf8_encode** or **utf8_decode** functions depending of the codification of your database.

As an example:

**Energía** is retrieved as **Energ\u00eda**

Thank you again for your quickly and patient help :)

**Comment by Finnb8r** [comment]
Great news !
I'll actually bypass the whole tmp file on a next commit to avoid any errors that should not be a problem.
Thanks for the UTF-8 suggestion, I will make sure to double check that.
Thank you again for your feedback and all my apologies for the issues you encountered.
Good luck and have fun :)
