### ISSUE TITLE
Set account

### ISSUE THREAD

**Issue by emilagervigstarup** [Finnb8r/itunes-connect-sales-api-php#3]
I get:
You have access to more than one account. Please specify an account number in your properties file or on the command line. To see a list of accounts, run the command getAccounts.

How do I set an account? I know I can get them with $reporter->getAccounts().

**Comment by Finnb8r** [comment]
Hi Emil, 
Thank you for filing an issue and sorry about that, I have just commited a change to the main class which now contains a setAccount() method. Please pull the latest commit.

You can set a specific account either by using the account number : 
`$reporter = new iTunesSalesApi("user","password","idVendor");`
`$reporter->setAccount(1234567);`

or with the return of the getAccounts() method : 
`$reporter->setAccount($reporter->getAccounts()[0]);`

As I do not have an account with mulitple accounts myself, I am not 100% sure this works properly but the parameter is correct and it works for me when I specify the only account I have.
Let me know if all works out,
Cheers

**Comment by emilagervigstarup** [comment]
It did not work, I still get the error :/

**Comment by emilagervigstarup** [comment]
If I put a={account_number} in
$queryInput = "[p=Reporter.properties, a={account_number}, ".$this->_queryMode;

It seems to work :)

**Comment by Finnb8r** [comment]
That's great thanks for your feedback !
